/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facades;

import dtos.GroupMemberDTO;
import entities.GroupMember;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import utils.EMF_Creator;

/**
 *
 * @author Christian
 */
public class GroupMemberFacadeTest {

    private static EntityManagerFactory emf;
    private static GroupMemberFacade facade;

    static private int numberOfDummies = 5;
    GroupMember grpMeb1 = new GroupMember("Test1", "TestId1", GroupMember.ColorType.Yellow, "Mail.com");
    GroupMember grpMeb2 = new GroupMember("Test2", "TestId2", GroupMember.ColorType.Green, "Email.dk");

    public GroupMemberFacadeTest() {
    }

    //@BeforeAll
    public static void setUpClass() {
        emf = EMF_Creator.createEntityManagerFactory(
                "pu",
                "jdbc:mysql://localhost:3307/2020CA1_test",
                "dev",
                "ax2",
                EMF_Creator.Strategy.CREATE);
        facade = GroupMemberFacade.getGroupmemberFacade(emf);
    }

    /*   **** HINT **** 
        A better way to handle configuration values, compared to the UNUSED example above, is to store those values
        ONE COMMON place accessible from anywhere.
        The file config.properties and the corresponding helper class utils.Settings is added just to do that. 
        See below for how to use these files. This is our RECOMENDED strategy
     */
    @BeforeAll
    public static void setUpClassV2() {
        emf = EMF_Creator.createEntityManagerFactory(EMF_Creator.DbSelector.TEST, EMF_Creator.Strategy.DROP_AND_CREATE);
        facade = GroupMemberFacade.getGroupmemberFacade(emf);
    }

    @AfterAll
    public static void tearDownClass() {
//        Clean up database after test is done or use a persistence unit with drop-and-create to start up clean on every test
    }

    // Setup the DataBase in a known state BEFORE EACH TEST
    @BeforeEach
    public void setUp() {
        EntityManager em = emf.createEntityManager();

        try {

            em.getTransaction().begin();
            em.createNamedQuery("GroupMember.deleteAllRows").executeUpdate();

            // what to presist to DB
            em.persist(grpMeb1);
            em.persist(grpMeb2);

            // what to commit
            em.getTransaction().commit();
        } // must allways close transations. 
        finally {
            em.close();
        }
    }

    @AfterEach
    public void tearDown() {
//        Remove any data after each test was run
    }
//    GroupMember grpMeb1 = new GroupMember("Test1", "TestId1", GroupMember.ColorType.Yellow, "Mail.com");
//    GroupMember grpMeb2 = new GroupMember("Test2", "TestId2", GroupMember.ColorType.Green, "Email.dk");
    
    public void findGroupMemberById(long id) {
        System.out.println("FindGroupMemberbyId");
        GroupMember grp1 = facade.findGroupMemberById(1);
        GroupMember expected = (grp1 == grpMeb1)? grpMeb1: grpMeb2;
        //GroupMemberDTO expected = new GroupMemberDTO(id, grp1.getName(), grp1.getStudentId(), grp1.getColor());
        assertEquals(expected, facade.findGroupMemberById(id), "Expects 2 rows in the database");
        System.out.println("expected: " + expected +" Was: " +facade.findGroupMemberById(id));
    }

    /**
     * Test to see if number of expected groupMebers rows where added to DB
     */
    @Test
    public void GroupMemberCountTest() {
        System.out.println("allGroupMembers");
        assertEquals(2, facade.getGroupMemberCount(), "Expects 2 rows in the database");
    }

//    @Test
//    public void getAllGroupMembers() {
//        System.out.println("allGroupMembers");
//        List<GroupMember> list = new ArrayList();
//        list.add(grpMeb1);
//        list.add(grpMeb2);
//        List<GroupMember> list2 = facade.getAllGroupMembers();
//        // need to find a way to find identification id generated by db
//        assertEquals(list, facade.getAllGroupMembers(), "Expects the 2 test persons");
//    }

}
